### ISSUE TITLE
lambda expressions are not supported in -source 7

### ISSUE THREAD

**Issue by AnthonyRootdevs** [StartApp-SDK/flutter-plugin#1]
/.pub-cache/hosted/pub.dartlang.org/startapp_sdk-0.1.5/android/src/main/java/com/startapp/flutter/sdk/StartAppSdkPlugin.java:90: error: lambda expressions are not supported in -source 7
                        new StartAppViewFactory<>(() -> new StartAppFlutterBanner(bannerAdKeeper)));
                                                     ^

  (use -source 8 or higher to enable lambda expressions)
1 error

**Comment by kayson3** [comment]
Have you solved it?

Am getting the same error

**Comment by okstartapp** [comment]
Solved in version 0.1.6

**Comment by kayson3** [comment]
👍

**Comment by AnthonyRootdevs** [comment]
i was fixed this problem with this code

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

but now u dont need to chnage anything just update the package...

thank you Team StartApp for support

**Comment by AnthonyRootdevs** [comment]
Team StartApp for support
