### ISSUE TITLE
Failed to load BANNED ad: NO FILL

### ISSUE THREAD

**Issue by arieffajargemilang** [StartApp-SDK/flutter-plugin#6]
I'm trying to run a sample application from

https://github.com/StartApp-SDK/flutter-plugin 

and I use my own app_id. 

but there is an error 
Failed to load BANNED ad: NO FILL 

every time I try, I always get the same error.

I didn't change any code other than app_id in manifest.xml 

please give answer

![IMG_20220802_170912.jpg](https://user-images.githubusercontent.com/53034733/182363184-a69f97c1-49d3-4392-928f-b46c1ce6abdc.jpg)

![IMG_20220802_170641.jpg](https://user-images.githubusercontent.com/53034733/182363301-7d64fbb9-be83-49cc-8469-ac4d292971f7.jpg)

**Comment by okstartapp** [comment]
Make sure you put your app ID value into `AndroidManifest.xml`, [at this line](https://github.com/StartApp-SDK/flutter-plugin/blob/master/example/android/app/src/main/AndroidManifest.xml#L11).

**Comment by arieffajargemilang** [comment]
> Make sure you put your app ID value into `AndroidManifest.xml`, [at this line](https://github.com/StartApp-SDK/flutter-plugin/blob/master/example/android/app/src/main/AndroidManifest.xml#L11).

I've changed with my app id

**Comment by okstartapp** [comment]
Please, submit a request to our support team by using [this page](https://support.start.io/hc/en-us/requests/new). Include your app ID there and mention that your issue is related to Flutter.

**Comment by arieffajargemilang** [comment]
> Please, submit a request to our support team by using [this page](https://support.start.io/hc/en-us/requests/new). Include your app ID there and mention that your issue is related to Flutter.

ok..
