### ISSUE TITLE
Your app includes non compliant SDK com.startapp:inapp-sdk version

### ISSUE THREAD

**Issue by barchinvictor** [StartApp-SDK/flutter-plugin#7]
Hi! Our client's application received an email that an issue was found. Please update the flutter plugin to use SDK com.startapp:inapp-sdk version 4.10.1 or below. After November 22, the user's application will have problems.

"_Issue found: [User Data](https://support.google.com/googleplay/android-developer/answer/10144311). Policy Issue by SDK
Your app com.duba... version code 1004 includes SDK com.startapp:inapp-sdk, or an SDK that one of your libraries depends on, potentially facilitates the transmission or collection of installed packages without meeting the prominent disclosure guidelines and/or privacy policy guidelines.

Please ensure that you are being transparent in how you handle user data (e.g., information collected from or about a user, including device information). That means disclosing your app's access, collection, use, and sharing of the data, and limiting the use of the data to the purposes disclosed. If your app handles sensitive user data, then you must follow the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) Policy.

Starting from November 22, 2022 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) Policy will be blocked from release. You may consider upgrading to a policy-compliant version of this SDK that does not include the violating code, if available from your SDK provider; moving to another SDK; or removing this SDK.

According to the information provided by your SDK provider, you may consider upgrading to 4.10.1. Please consult the SDK provider for further information.

ACTION REQUIRED: Upload a compliant version AND deactivate the noncompliant version

Read through the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policies for more details, and how to submit an updated app for review [here](https://support.google.com/googleplay/android-developer/answer/2477981#resubmit). If you do not deactivate the non-compliant APK, all your live APKs may be removed due to this non-compliant APK.

Check that your app is compliant with all other[Developer Program Policies](https://play.google.com/about/developer-content-policy). Additional enforcement could occur if there are further policy violations.

If you've reviewed the policy and feel our decision may have been in error, please reach out to our[policy support team](https://support.google.com/googleplay/android-developer/contact/appwarning?ts=sdk&src=com.startapp:inapp-sdk). Please Reply Thank you_"

**Comment by StartApp-SDK** [comment]
The most recent version of Flutter plugin is 1.0.1 which depends on the com.startapp:inapp-sdk:5.0.0 and it is compliant.
